version: '3.8'

services:
  api1:
    build: .
    volumes:
      - .:/usr/local/app
    ports:
      - 8000
    environment:
      - DB_NAME=rinha-backend
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_HOST=db
      - WEB_PORT=8000
    command: go run cmd/api/main.go
    depends_on: 
      - db
  api2:
    build: .
    volumes:
      - .:/usr/local/app
    ports:
      - 8000
    environment:
      - DB_NAME=rinha-backend
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_HOST=db
      - WEB_PORT=8000
    command: go run cmd/api/main.go
    depends_on: 
      - db
  nginx: 
    image: nginx:latest
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 9999:80
    depends_on:
      - api1
      - api2
  db:
    image: postgres:alpine
    ports: 
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rinha-backend
  pgadmin:
    image: dpage/pgadmin4
    tty: true
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db

volumes:
  postgres-db:
