version: '3.8'

services:
  db:
    image: postgres:alpine
    network_mode: host
    volumes:
      - postgres-db:/var/lib/postresql/data
      - ./.docker/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rinha-backend
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
  api1: &api
    build: .
    network_mode: host
    restart: always
    environment:
      - DB_NAME=rinha-backend
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_HOST=localhost
      - WEB_PORT=8001
    depends_on: 
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  api2:
    <<: *api
    environment:
      - WEB_PORT=8000
      - DB_HOST=localhost
  nginx: 
    image: nginx:latest
    network_mode: host
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
volumes:
  postgres-db:
